config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :concerts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "concerts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concert.rb
class Concert < ApplicationRecord
    belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :concert

    def q_concerts
        self.contents.count
    end

    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_action :set_concert, only: %i[ show edit update destroy ]

  # GET /concerts or /concerts.json
  def index
    @concerts = Concert.all
  end

  # GET /concerts/1 or /concerts/1.json
  def show
  end

  # GET /concerts/new
  def new
    @concert = Concert.new
    @groups = Group.all
  end

  # GET /concerts/1/edit
  def edit
  end

  # POST /concerts or /concerts.json
  def create
    @concert = Concert.new(concert_params)

    respond_to do |format|
      if @concert.save
        format.html { redirect_to concert_url(@concert), notice: "Concert was successfully created." }
        format.json { render :show, status: :created, location: @concert }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concerts/1 or /concerts/1.json
  def update
    respond_to do |format|
      if @concert.update(concert_params)
        format.html { redirect_to concert_url(@concert), notice: "Concert was successfully updated." }
        format.json { render :show, status: :ok, location: @concert }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concerts/1 or /concerts/1.json
  def destroy
    @concert.destroy

    respond_to do |format|
      format.html { redirect_to concerts_url, notice: "Concert was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concert
      @concert = Concert.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def concert_params
      params.require(:concert).permit(:attendance, :duration, :placedate)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]

  # GET /groups or /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1 or /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to group_url(@group), notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:name, :crew, :debut_date, :date, :group_type, :integer)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/concerts/_concert.html.erb
<div id="<%= dom_id concert %>">
  <p>
    <strong>Attendance:</strong>
    <%= concert.attendance %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= concert.duration %>
  </p>

  <p>
    <strong>Placedate:</strong>
    <%= concert.placedate %>
  </p>

</div>

app/views/concerts/_form.html.erb
<%= form_with(model: concert) do |form| %>
  <% if concert.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(concert.errors.count, "error") %> prohibited this concert from being saved:</h2>

      <ul>
        <% concert.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
      <%= form.label :groups %>
      <%= form.select :group_id, options_from_collection_for_select(@groups, :id, :name) %>
  </div>

  <div>
    <%= form.label :attendance, style: "display: block" %>
    <%= form.number_field :attendance %>
  </div>

  <div>
    <%= form.label :duration, style: "display: block" %>
    <%= form.number_field :duration %>
  </div>

  <div>
    <%= form.label :placedate, style: "display: block" %>
    <%= form.datetime_field :placedate %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/concerts/edit.html.erb
<h1>Editing concert</h1>

<%= render "form", concert: @concert %>

<br>

<div>
  <%= link_to "Show this concert", @concert %> |
  <%= link_to "Back to concerts", concerts_path %>
</div>

app/views/concerts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Concerts</h1>

<div id="concerts">
  <% @concerts.each do |concert| %>
    <%= render concert %>
    <p>
      <%= link_to "Show this concert", concert %>
    </p>
  <% end %>
</div>

<%= link_to "New concert", new_concert_path %>

app/views/concerts/new.html.erb
<h1>New concert</h1>

<%= render "form", concert: @concert %>

<br>

<div>
  <%= link_to "Back to concerts", concerts_path %>
</div>

app/views/concerts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @concert %>

<div>
  <%= link_to "Edit this concert", edit_concert_path(@concert) %> |
  <%= link_to "Back to concerts", concerts_path %>

  <%= button_to "Destroy this concert", @concert, method: :delete %>
</div>

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :crew, style: "display: block" %>
    <%= form.number_field :crew %>
  </div>

  <div>
        <%= form.label :groups %>
        <%= form.select :group_id, options_from_collection_for_select(@groups, :id, :name) %>
  </div>


  <div>
    <%= form.label :debut_date, style: "display: block" %>
    <%= form.text_field :debut_date %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.text_field :date %>
  </div>

  <div>
    <%= form.label :group_type, style: "display: block" %>
    <%= form.text_field :group_type %>
  </div>

  <div>
    <%= form.label :integer, style: "display: block" %>
    <%= form.text_field :integer %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>">
  <p>
    <strong>Name:</strong>
    <%= group.name %>
  </p>

  <p>
    <strong>Crew:</strong>
    <%= group.crew %>
  </p>

  <p>
    <strong>Debut date:</strong>
    <%= group.debut_date %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= group.date %>
  </p>

  <p>
    <strong>Group type:</strong>
    <%= group.group_type %>
  </p>

  <p>
    <strong>Integer:</strong>
    <%= group.integer %>
  </p>

</div>

<th> concerts:</th>
</td>
   <% group.concerts.each do |concert| %>
     <tbody>
        <tr>
           <td><%= l concert.date, format: "%d-%b-%Y" %></td>
           <td><%= concert.place %></td>
           <td><%= concert.attendance %>  Personas</td>
           <td><%= concert.duration %> Hora(s)</td>
        </tr>
    </tbody>
</td>

<%end%>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Groups</h1>

<div id="groups">
  <% @groups.each do |group| %>
    <%= render group %>
    <p>
      <%= link_to "Show this group", group %>
    </p>
  <% end %>
</div>

<%= link_to "New group", new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group %>

<div>
  <%= link_to "Edit this group", edit_group_path(@group) %> |
  <%= link_to "Back to groups", groups_path %>

  <%= button_to "Destroy this group", @group, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DesafioProductoraDeEventos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

  </head>

  <body>
    <%= yield %>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>